# Site settings
title: neiro Î» Web development, functional programming
email: "mailto:neiro.mail@gmail.com"
description: >
  My personal website, blog and portfolio
baseurl: ""
url: "http://neiro.io"
source_url: "https://github.com/ne1ro/neiro.io"
twitter: "https://twitter.com/ne1ro"
github: "https://github.com/ne1ro"
linkedin: "https://ru.linkedin.com/in/neiro"

# Build settings
markdown: kramdown

exclude:
  - bower.json
  - LICENSE
  - Gemfile
  - Guardile
  - Gemfile.lock
  - vendor

# Jekyll assets configuration
assets:
  js_compressor: uglifier
  css_compressor: sass

navigation:
  - title: Blog
    url: /
  - title: Projects
    url: /projects
  - title: About me
    url: /about
  - title: Contact
    url: /contact
