# Site settings
title: neiro Î» Web development, functional programming
email: "mailto:neiro.mail@gmail.com"
description: >
  My personal website, blog and portfolio
baseurl: ""
url: "http://neiro.io"
source_url: "https://github.com/ne1ro/neiro.io"
twitter: "https://twitter.com/ne1ro"
github: "https://github.com/ne1ro"
linkedin: "https://linkedin.com/in/neiro"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - bower.json
  - LICENSE
  - Gemfile
  - Guardile
  - Gemfile.lock
  - vendor

# Tag configuration
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Jekyll assets configuration
assets:
  js_compressor: uglifier
  css_compressor: sass

navigation:
  - title: Blog
    url: /
  - title: Projects
    url: /projects
  - title: About me
    url: /about
  - title: Contact
    url: /contact
