# Site settings
title: neiro Î» Web development professional
email: neiro.mail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website, blog and portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neiro.io" # the base hostname & protocol for your site
twitter_username: ne1ro
github_username:  ne1ro

# Build settings
markdown: kramdown

exclude:
  - bower.json
  - LICENSE
  - Gemfile
  - Guardile
  - Gemfile.lock
  - vendor

gems:
  - jekyll-assets

safe: false

# Jekyll assets configuration
assets:
  js_compressor:  uglifier
  css_compressor: sass
